// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeWwR83jR_11n_oGZ4nXp424ZMMR8yOkQ',
    appId: '1:657916208451:web:ca3275dbf0419f244b7bf6',
    messagingSenderId: '657916208451',
    projectId: 'jyotishasha-app-10gob6',
    authDomain: 'jyotishasha-app-10gob6.firebaseapp.com',
    storageBucket: 'jyotishasha-app-10gob6.firebasestorage.app',
    measurementId: 'G-Q1DG6Z0CL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpFzFZ49NiPU8CSGl-JTVvfNVTIev8Pk',
    appId: '1:657916208451:android:7f9db9bf1f3f7e2b4b7bf6',
    messagingSenderId: '657916208451',
    projectId: 'jyotishasha-app-10gob6',
    storageBucket: 'jyotishasha-app-10gob6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeWwR83jR_11n_oGZ4nXp424ZMMR8yOkQ',
    appId: '1:657916208451:web:11ee2fcc1f5832d94b7bf6',
    messagingSenderId: '657916208451',
    projectId: 'jyotishasha-app-10gob6',
    authDomain: 'jyotishasha-app-10gob6.firebaseapp.com',
    storageBucket: 'jyotishasha-app-10gob6.firebasestorage.app',
    measurementId: 'G-JTBS46MR2S',
  );

}