// 🌟 main.dart
// ---------------------------------------------------------
// Entry point for Jyotishasha Flutter App
// ---------------------------------------------------------
// - Initializes Firebase
// - Loads environment variables (.env)
// - Initializes timezone database
// - Logs safely using developer.log()
// - Loads the root JyotishashaApp widget
// ---------------------------------------------------------

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'app/app.dart'; // root MaterialApp
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'dart:developer' as developer;
import 'package:timezone/data/latest.dart' as tz;

Future<void> main() async {
  // ✅ Ensure Flutter engine & bindings are ready
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Load environment variables
  await dotenv.load(fileName: ".env");

  // ✅ Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // ✅ Initialize timezone database
  tz.initializeTimeZones();

  // 🧭 Professional logging (only shows in debug console)
  developer.log("BASE_URL: ${dotenv.env['BASE_URL']}", name: 'ENV');

  // 🚀 Run main application
  runApp(const JyotishashaApp());
}
