// 🌟 main.dart
// ---------------------------------------------------------
// Entry point for Jyotishasha Flutter App
// ---------------------------------------------------------
// - Initializes Firebase
// - Loads the root JyotishashaApp widget
// ---------------------------------------------------------

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'app/app.dart'; // root MaterialApp

Future<void> main() async {
  // ✅ Ensure Flutter engine & Firebase are ready
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 🚀 Run main application
  runApp(const JyotishashaApp());
}
